### ISSUE TITLE
Custom colour support

### ISSUE THREAD

**Issue by CuriouslyCurious** [Tmplt/bookwyrm#43]
Having the colours be customizable would be a cool feature to have. This could be achieved through using the terminal's own colours: https://stackoverflow.com/questions/18551558/how-to-use-terminal-color-palette-with-curses#22166613

**Comment by Tmplt** [comment]
NCurses colour pairs are used, so custom colour support is probably already implemented.

**Comment by Tmplt** [comment]
On a related tangent, [NO_COLOR](https://no-color.org/) should be supported.

**Comment by Tmplt** [comment]
Custom colours are indeed supported.
