### ISSUE TITLE
The Big List of Small Issues

### ISSUE THREAD

**Issue by Tmplt** [Tmplt/bookwyrm#53]
For `v0.5.0`, this issue shall contain lists of smaller issues that are not big enough to warrant its own ticket. All of these issues should be fixed before next major/minor release.

- [x] libgen.py: titles are recorded with an added space at the end, which makes written files have an extra space in it;
- [x] when writing files with unset year, `(-1)` is in the filename, instead of being omitted;
- [x] if a plugin is found, but any of its imports fail, bookwyrm just complains that it couldn't find any plugins;
  - [x] flush plugin handler logs to std[out,cerr];
  - [x] respect [--debug] and prefix the message with the log level, alá the log screen;
- [x] the `--year` option is ignored;
- [x] it's not clear if there are still plugins running in the background (some plugin status should be added to the footer);
  - [x] improve message, state end of search when no plugins are running;
  - [x] plugin counter may be non-zero when it shouldn't be; the backend should update the frontend when a plugin terminates;
- [x] fuzzy matches in `bool item::matches()` are currently hard-coded for `>75`% — a cli option should probably be added to set the accuracy (how matching work should probably be explained somewhere too);
  - [x] make `core::plugin_handler` take plugin paths and fuzzy threshold via options struct;
  - [x] add `--accuracy` option;
- [x] `libgen.py` doesn't seem to work, investigate;

and more to come...

**Comment by CuriouslyCurious** [comment]
I'll start bug-testing tomorrow. ;)

**Comment by Tmplt** [comment]
As for the some times rogue space in the tail of the title from `libgen.py`, prefixed and suffixed whitespace should probably be cleared when creating the actual item. This can be done in each component's `get_value()`.

**Comment by Tmplt** [comment]
Closing this because it lacks the structure multiple separate issues would have.
