### ISSUE TITLE
master branch does not build

### ISSUE THREAD

**Issue by tmplt** [tmplt/bookwyrm#93]
ac438b02d9c874f3f59ea702c7fdab1e820c6d9e does not build; our compilation options are too strict. Commenting them out in `cmake/build/core.cmake` enabled a build, but that is no fix.

**Comment by joshcho** [comment]
I am trying to install with bookwyrm-git, but unable to install. I tried commenting the warnings line in core.cmake, but to no avail. I am getting final link failed: bad value. Is this expected behavior?

**Comment by tmplt** [comment]
`master` should always build and link, but the project has been effectively unmaintained since the last commit so I'm not surprised that it has bit-rotted further. The AUR package, which I presumed you used, should really be removed. It's likely that the libgen parser also is broken; libgen is a bit of a moving target, which is the main reason why I haven't worked any further on bookwyrm.

I'm considering archiving the repo with a deprecation notice, but if you wish to contribute I'll handle PRs. Build/link errors should be trivial. If `plugins/libgen.py` fails running it directly can help with debugging.

**Comment by joshcho** [comment]
Thanks for the reply. I think I am having some errors with the dependencies. I am getting 'void PyEval_InitThreads()' is deprecated warning, and don't know how to disable -Werror=deprecated-declarations for pybind11. Not sure where to look.

**Comment by joshcho** [comment]
Thanks for the reply. I have fixed all the build warnings, but it seems running ./bookwyrm cannot find pybookwyrm (there is a sense in which I don't really understand the project structure). Anything I may be missing?

**Comment by tmplt** [comment]
Is the symlink in `src/plugins/` valid?

**Comment by tmplt** [comment]
>if you wish to contribute I'll handle PRs.

This is no longer the case: I will no longer maintain the repository and it will be archived. Feel free to fork the project if you wish to take up the torch.
